"""Sphinx configuration for the exporgo documentation site.

Authored for a ReadTheDocs build (see ``.readthedocs.yaml`` at the repository root).
The API reference is generated by autodoc from each package's public ``__all__``;
pydantic models render through autodoc_pydantic, and Google-style docstrings through
napoleon. Pages are authored in MyST Markdown.
"""

import importlib.metadata

# -- Project information -----------------------------------------------------------------

project = "exporgo"
author = "Darik A. O'Neil"
# noinspection PyShadowingBuiltins
copyright = "2026, Darik A. O'Neil"

# Pull the version from the installed distribution metadata (derived from pyproject.toml),
# rather than importing the package, so the docs version tracks the packaged version.
release = importlib.metadata.version("exporgo")
version = ".".join(release.split(".")[:2])

# -- General configuration ---------------------------------------------------------------

extensions = [
    "myst_parser",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosectionlabel",
    "sphinx.ext.napoleon",
    "sphinx.ext.autosummary",
    "sphinx.ext.viewcode",
    "sphinx.ext.intersphinx",
    "sphinx_autodoc_typehints",
    "sphinxcontrib.autodoc_pydantic",
    "sphinx.ext.coverage",
    "sphinx.ext.todo"
]

exclude_patterns = []

# -- MyST Markdown -----------------------------------------------------------------------

myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "smartquotes",
]
myst_heading_anchors = 3

# -- HTML output -------------------------------------------------------------------------

html_theme = "sphinx_rtd_theme"
html_static_path = ["_static"]
html_title = f"exporgo {version}"

# -- autodoc / napoleon / type hints -----------------------------------------------------

autodoc_default_options = {
    "members": True,
    "show-inheritance": True,
    "member-order": "bysource",
}
autodoc_typehints = "description"
autoclass_content = "class"

napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_include_init_with_doc = False

typehints_defaults = 'comma'
always_document_param_types = True
typehints_fully_qualified = False
typehints_document_rtype = True
always_use_bars_union = True
simplify_optional_unions = False
typehints_use_signature = False
typehints_use_signature_return = False

# -- autodoc_pydantic --------------------------------------------------------------------
# Keep the rendered models focused on the fields and their constraints; suppress the noisier
# JSON-schema, config, and validator dumps.

autodoc_pydantic_model_show_field_summary = True
autodoc_pydantic_field_list_validators = False
autodoc_pydantic_model_show_json = True
autodoc_pydantic_model_show_config_summary = True
autodoc_pydantic_model_show_validator_members = True
autodoc_pydantic_model_show_validator_summary = True

# -- intersphinx -------------------------------------------------------------------------
# Cross-references to the standard library and pydantic. Missing inventories degrade to a
# warning (the build command does not treat warnings as errors), so an offline local build
# still succeeds.

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "pydantic": ("https://pydantic.dev/docs/validation/latest/", None),
    "numpy": ('https://numpy.org/doc/1.24/', None),
    "polars": ('https://docs.pola.rs/api/python/stable/', None),
    "xarray": ('https://docs.xarray.dev/en/stable/', None),
}

pygments_style = "sphinx"
typehints_use_signature = False
typehints_use_signature_return = False
todo_include_todos = True
language = "en"
coverage_show_missing_items = True
